<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\Icon\RMCL4.Logo.Big.ico</ApplicationIcon>
    </PropertyGroup>

    <PropertyGroup>
      <BuildTimestamp>$([System.DateTime]::UtcNow.ToString("yyyy-MM-dd HH:mm:ss"))</BuildTimestamp>
    </PropertyGroup>

    <ItemGroup>
      <AssemblyAttribute Include="System.Reflection.AssemblyMetadata">
        <_Parameter1>BuildTimestamp</_Parameter1>
        <_Parameter2>$(BuildTimestamp)</_Parameter2>
      </AssemblyAttribute>
    </ItemGroup>


    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
        <Folder Include="ViewModels\Page\" />
        <Folder Include="Views\Style\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.7" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.7">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Properties\Resource.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Resource.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Window\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resource.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resource.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <None Remove="Properties\Resource.ru.xml" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LiteSkinViewer\LiteSkinViewer.2D\LiteSkinViewer.2D.csproj" />
      <ProjectReference Include="..\OnePointUI.Avalonia\src\OnePointUI.Avalonia\OnePointUI.Avalonia.csproj" />
      <ProjectReference Include="..\OverrideLauncher.Core\src\OverrideLauncher.Core\OverrideLauncher.Core.csproj" />
      <ProjectReference Include="..\RemoteOnline\RemoteOnline\RemoteOnline.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AvaloniaResource Update="Assets\Text\OpenSourceProject.md">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </AvaloniaResource>
    </ItemGroup>
</Project>
