//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMCL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMCL.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL.
        /// </summary>
        public static string App_WindowTitle {
            get {
                return ResourceManager.GetString("App.WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string MainPage_Download {
            get {
                return ResourceManager.GetString("MainPage.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本列表.
        /// </summary>
        public static string MainPage_GameList {
            get {
                return ResourceManager.GetString("MainPage.GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string MainPage_Home {
            get {
                return ResourceManager.GetString("MainPage.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动游戏.
        /// </summary>
        public static string MainPage_Launch {
            get {
                return ResourceManager.GetString("MainPage.Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MainPage_Setting {
            get {
                return ResourceManager.GetString("MainPage.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我们.
        /// </summary>
        public static string Settings_About_Description {
            get {
                return ResourceManager.GetString("Settings.About.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string Settings_Account {
            get {
                return ResourceManager.GetString("Settings.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏账户与启动器账户.
        /// </summary>
        public static string Settings_Account_Description {
            get {
                return ResourceManager.GetString("Settings.Account.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Settings_Help {
            get {
                return ResourceManager.GetString("Settings.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助与帮助.
        /// </summary>
        public static string Settings_Help_Description {
            get {
                return ResourceManager.GetString("Settings.Help.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        public static string Settings_Launch {
            get {
                return ResourceManager.GetString("Settings.Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器与游戏启动行为.
        /// </summary>
        public static string Settings_Launch_Description {
            get {
                return ResourceManager.GetString("Settings.Launch.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即重启.
        /// </summary>
        public static string Settings_Restart {
            get {
                return ResourceManager.GetString("Settings.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性化.
        /// </summary>
        public static string Settings_Style {
            get {
                return ResourceManager.GetString("Settings.Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器个性化设置.
        /// </summary>
        public static string Settings_Style_Description {
            get {
                return ResourceManager.GetString("Settings.Style.Description", resourceCulture);
            }
        }
    }
}
