//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMCL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RMCL.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL.
        /// </summary>
        public static string App_WindowTitle {
            get {
                return ResourceManager.GetString("App.WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载.
        /// </summary>
        public static string MainPage_Download {
            get {
                return ResourceManager.GetString("MainPage.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本列表.
        /// </summary>
        public static string MainPage_GameList {
            get {
                return ResourceManager.GetString("MainPage.GameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string MainPage_Home {
            get {
                return ResourceManager.GetString("MainPage.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未固定游戏.
        /// </summary>
        public static string MainPage_Home_NoPin {
            get {
                return ResourceManager.GetString("MainPage.Home.NoPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动游戏.
        /// </summary>
        public static string MainPage_Launch {
            get {
                return ResourceManager.GetString("MainPage.Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string MainPage_Setting {
            get {
                return ResourceManager.GetString("MainPage.Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鸣谢.
        /// </summary>
        public static string OtherAboutUs_Acknowledgement {
            get {
                return ResourceManager.GetString("OtherAboutUs.Acknowledgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 使用了来自 bangbang93 提供的 BMCLAPI 作为部分 Minecraft 资源下载源。.
        /// </summary>
        public static string OtherAboutUs_Acknowledgement_BMCLAPI {
            get {
                return ResourceManager.GetString("OtherAboutUs.Acknowledgement.BMCLAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 组件库.
        /// </summary>
        public static string OtherAboutUs_ComponentLibrary {
            get {
                return ResourceManager.GetString("OtherAboutUs.ComponentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 使用了 OnePoint UI 作为用户交互风格.
        /// </summary>
        public static string OtherAboutUs_ComponentLibrary_OnePoint {
            get {
                return ResourceManager.GetString("OtherAboutUs.ComponentLibrary.OnePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三方组件库.
        /// </summary>
        public static string OtherAboutUs_ComponentLibrary_OpenSource {
            get {
                return ResourceManager.GetString("OtherAboutUs.ComponentLibrary.OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 使用的第三方开源库.
        /// </summary>
        public static string OtherAboutUs_ComponentLibrary_OpenSource_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.ComponentLibrary.OpenSource.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 使用了 OverrideLauncher.Core 作为游戏启动核心.
        /// </summary>
        public static string OtherAboutUs_ComponentLibrary_OverrideLauncherCore {
            get {
                return ResourceManager.GetString("OtherAboutUs.ComponentLibrary.OverrideLauncherCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发者.
        /// </summary>
        public static string OtherAboutUs_Developer {
            get {
                return ResourceManager.GetString("OtherAboutUs.Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 本体：Dime.
        /// </summary>
        public static string OtherAboutUs_Developer_Body {
            get {
                return ResourceManager.GetString("OtherAboutUs.Developer.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 启动核心：Dime.
        /// </summary>
        public static string OtherAboutUs_Developer_LaunchCore {
            get {
                return ResourceManager.GetString("OtherAboutUs.Developer.LaunchCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户交互体验指导：DrMing.
        /// </summary>
        public static string OtherAboutUs_Developer_UserInteractionExperienceGuidance {
            get {
                return ResourceManager.GetString("OtherAboutUs.Developer.UserInteractionExperienceGuidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 灵感.
        /// </summary>
        public static string OtherAboutUs_Inspiration {
            get {
                return ResourceManager.GetString("OtherAboutUs.Inspiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 内部分设计风格、动画参考 LauncherX.
        /// </summary>
        public static string OtherAboutUs_Inspiration_LauncherX {
            get {
                return ResourceManager.GetString("OtherAboutUs.Inspiration.LauncherX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMCL 内部分页面设计、功能参考 WonderLab、BakaXL.
        /// </summary>
        public static string OtherAboutUs_Inspiration_WonderLabBakaXL {
            get {
                return ResourceManager.GetString("OtherAboutUs.Inspiration.WonderLabBakaXL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景.
        /// </summary>
        public static string OtherAboutUs_Style_Background {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器窗口背景.
        /// </summary>
        public static string OtherAboutUs_Style_Background_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Background.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string OtherAboutUs_Style_Color {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 强调色与深浅模式.
        /// </summary>
        public static string OtherAboutUs_Style_Color_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Color.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string OtherAboutUs_Style_Language {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言 / Language.
        /// </summary>
        public static string OtherAboutUs_Style_Language_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Language.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音乐.
        /// </summary>
        public static string OtherAboutUs_Style_Music {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景音乐设置.
        /// </summary>
        public static string OtherAboutUs_Style_Music_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.Music.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题包制作.
        /// </summary>
        public static string OtherAboutUs_Style_ThemePackProduction {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.ThemePackProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制作 [Round Studio] 通用格式主题包.
        /// </summary>
        public static string OtherAboutUs_Style_ThemePackProduction_Description {
            get {
                return ResourceManager.GetString("OtherAboutUs.Style.ThemePackProduction.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内部版本.
        /// </summary>
        public static string OtherAboutUs_Version {
            get {
                return ResourceManager.GetString("OtherAboutUs.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于我们.
        /// </summary>
        public static string Settings_About_Description {
            get {
                return ResourceManager.GetString("Settings.About.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 账户.
        /// </summary>
        public static string Settings_Account {
            get {
                return ResourceManager.GetString("Settings.Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 游戏账户与启动器账户.
        /// </summary>
        public static string Settings_Account_Description {
            get {
                return ResourceManager.GetString("Settings.Account.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Settings_Help {
            get {
                return ResourceManager.GetString("Settings.Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 辅助与帮助.
        /// </summary>
        public static string Settings_Help_Description {
            get {
                return ResourceManager.GetString("Settings.Help.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动.
        /// </summary>
        public static string Settings_Launch {
            get {
                return ResourceManager.GetString("Settings.Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器与游戏启动行为.
        /// </summary>
        public static string Settings_Launch_Description {
            get {
                return ResourceManager.GetString("Settings.Launch.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立即重启.
        /// </summary>
        public static string Settings_Restart {
            get {
                return ResourceManager.GetString("Settings.Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个性化.
        /// </summary>
        public static string Settings_Style {
            get {
                return ResourceManager.GetString("Settings.Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景样式.
        /// </summary>
        public static string Settings_Style_Background_BackgroundModel {
            get {
                return ResourceManager.GetString("Settings.Style.Background.BackgroundModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器背景样式.
        /// </summary>
        public static string Settings_Style_Background_BackgroundModel_Description {
            get {
                return ResourceManager.GetString("Settings.Style.Background.BackgroundModel.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 材质.
        /// </summary>
        public static string Settings_Style_Background_Material {
            get {
                return ResourceManager.GetString("Settings.Style.Background.Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电路板.
        /// </summary>
        public static string Settings_Style_Background_Material_CircuitBoard {
            get {
                return ResourceManager.GetString("Settings.Style.Background.Material.CircuitBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器背景材质.
        /// </summary>
        public static string Settings_Style_Background_Material_Description {
            get {
                return ResourceManager.GetString("Settings.Style.Background.Material.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 蜂窝.
        /// </summary>
        public static string Settings_Style_Background_Material_Honeycomb {
            get {
                return ResourceManager.GetString("Settings.Style.Background.Material.Honeycomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骷髅.
        /// </summary>
        public static string Settings_Style_Background_Material_Skull {
            get {
                return ResourceManager.GetString("Settings.Style.Background.Material.Skull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启动器个性化设置.
        /// </summary>
        public static string Settings_Style_Description {
            get {
                return ResourceManager.GetString("Settings.Style.Description", resourceCulture);
            }
        }
    }
}
