<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SupportedOSPlatformVersion>10.0.18362.0</SupportedOSPlatformVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OnePointUI.Avalonia\src\OnePointUI.Avalonia\OnePointUI.Avalonia.csproj" />
      <ProjectReference Include="..\Round.SDK\Round.SDK\Round.SDK.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Avalonia" Version="11.3.8" />
      <PackageReference Include="BedrockLauncher.Core" Version="25.8.31.956" />
    </ItemGroup>

</Project>
